# Generated by Django 5.0.3 on 2024-03-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alerts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src_ip", models.CharField(max_length=255)),
                ("dst_ip", models.CharField(max_length=255)),
                ("src_bytes", models.CharField(max_length=255)),
                ("dst_bytes", models.CharField(max_length=255)),
                ("flag", models.CharField(max_length=255)),
                ("service", models.CharField(max_length=255)),
                ("count", models.CharField(max_length=255)),
                ("same_srv_rate", models.CharField(max_length=255)),
                ("diff_srv_rate", models.CharField(max_length=255)),
                ("dst_host_srv_count", models.CharField(max_length=255)),
                ("dst_host_same_srv_rate", models.CharField(max_length=255)),
                ("dst_host_same_src_port_rate", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "alert",
            },
        ),
        migrations.CreateModel(
            name="TotalDevices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src_ip", models.CharField(max_length=255)),
                ("dst_ip", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "devices",
            },
        ),
    ]
