# Generated by Django 5.0.3 on 2024-03-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="totaldevices",
            name="type",
            field=models.CharField(default="normal", max_length=250),
        ),
    ]
