# Generated by Django 5.0.3 on 2024-03-28 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_totaldevices_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="alerts",
            name="datetime",
            field=models.CharField(
                default=datetime.datetime(2024, 3, 28, 12, 3, 39, 574488),
                max_length=255,
            ),
        ),
    ]
